networks:
  we4devs-network:
    driver: bridge


services:
  backend:
    image: smitbutle/we4devs-server
    container_name: backend
    env_file: ./Server/.env
    ports:
      - "6273:6273"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - we4devs-network

  frontend:
    build:
      context: ./Frontend
      args:
        - VITE_HOST=http://0.0.0.0:6273
    container_name: frontend
    environment:
      - VITE_HOST=http://0.0.0.0:6273
    ports:
      - "6173:5200"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - we4devs-network
